=== biannka/ASP_NET/XmlSample/App_Data/coffeeHouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CoffeeHouse">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="working_time"/>
        <xs:element ref="products"/>
        <xs:element minOccurs="0" ref="gift"/>
        <xs:element ref="contacts"/>
        <xs:element ref="employees"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.CoffeeHouse"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.CoffeeHouse">
    <xs:attribute name="id" use="required"/>
  </xs:attributeGroup>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="working_time" type="xs:string"/>
  <xs:element name="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="product"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="price"/>
        <xs:element ref="product_name"/>
        <xs:element minOccurs="0" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="coffee"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="food"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="image"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.product"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.product">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="image" type="xs:string"/>
  <xs:element name="price" type="xs:string"/>
  <xs:element name="product_name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="coffee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coffee_name"/>
        <xs:element ref="coffee_type"/>
        <xs:element minOccurs="0" ref="supplement_price"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.coffee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.coffee">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="drink_type" default="Гореща">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Гореща"/>
          <xs:enumeration value="Студена"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="supplement_type" default="Без">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Захар"/>
          <xs:enumeration value="Канела"/>
          <xs:enumeration value="Мляко"/>
          <xs:enumeration value="Сметана"/>
          <xs:enumeration value="Без"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="coffee_type" type="xs:string"/>
  <xs:element name="coffee_name" type="xs:string"/>
  <xs:element name="supplement_price" type="xs:string"/>
  <xs:element name="food">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="food_name">
          <xs:attributeGroup ref="attlist.food"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.food">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="food_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Солено"/>
          <xs:enumeration value="Сладко"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="food_name">
    <xs:sequence>
      <xs:element ref="food_name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="food_name" type="xs:string"/>
  <xs:element name="gift">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="gift_name">
          <xs:attributeGroup ref="attlist.gift"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.gift">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="gift_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Храна"/>
          <xs:enumeration value="Кафе"/>
          <xs:enumeration value="Отстъпка"/>
          <xs:enumeration value="Ваучер"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="gift_reason" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Редовен"/>
          <xs:enumeration value="Покупка"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="gift_name">
    <xs:sequence>
      <xs:element ref="gift_name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="gift_name" type="xs:string"/>
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location"/>
        <xs:element ref="phone"/>
        <xs:element ref="website"/>
        <xs:element ref="e-mail"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.contacts"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.contacts">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="phone" type="xs:string"/>
  <xs:element name="e-mail" type="xs:string"/>
  <xs:element name="website" type="xs:string"/>
  <xs:element name="location">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="country"/>
        <xs:element ref="city"/>
        <xs:element minOccurs="0" ref="street"/>
        <xs:element ref="building_number"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="country" type="xs:string"/>
  <xs:element name="city" type="xs:string"/>
  <xs:element name="street" type="xs:string"/>
  <xs:element name="building_number" type="xs:string"/>
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="employee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="emp_name"/>
        <xs:element ref="salary"/>
        <xs:element minOccurs="0" ref="age"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.employee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.employee">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="position" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Продавач"/>
          <xs:enumeration value="Готвач"/>
          <xs:enumeration value="Чистач"/>
          <xs:enumeration value="Управител"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="sex" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Мъж"/>
          <xs:enumeration value="Жена"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="emp_name" type="xs:string"/>
  <xs:element name="salary" type="xs:string"/>
  <xs:element name="age" type="xs:string"/>
</xs:schema>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_10.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="10">
  <name>Свежо Утро</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П100">
      <price>2лв</price>
      <product_name>Класическа Закуска</product_name>
      <coffee id="К101" supplement_type="Захар" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Еспресо</coffee_type>
        <supplement_price>0.5лв.</supplement_price>
      </coffee>
      <food id="Х102" food_type="Солено">
        <food_name>Сандвич</food_name>
      </food>
    </product>
    <product id="П101">
      <price>3лв</price>
      <product_name>Сладка Закуска</product_name>
      <coffee id="К1010" supplement_type="Захар" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Еспресо</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
      <food id="Х1010" food_type="Сладко">
        <food_name>Кексче</food_name>
      </food>
    </product>
    <product id="П102">
      <price>4лв</price>
      <product_name>Свежа Закуска</product_name>
      <coffee id="К1020" supplement_type="Захар" drink_type="Студена">
        <coffee_name>Фрапе</coffee_name>
        <coffee_type>Нескафе</coffee_type>
        <supplement_price>0.5лв.</supplement_price>
      </coffee>
      <food id="Х1020" food_type="Сладко">
        <food_name>Сладолед и плодове</food_name>
      </food>
    </product>
    <product id="П103">
      <price>5лв</price>
      <product_name>Здравословна Закуска</product_name>
      <coffee id="П1030" supplement_type="Мляко" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Зелен Рдесн</coffee_type>
        <supplement_price>0.5лв</supplement_price>
      </coffee>
      <food id="Х1030" food_type="Сладко">
        <food_name>Зърнена закуска с плодове</food_name>
      </food>
    </product>
  </products>
  <gift id="Г10" gift_type = "Ваучер" gift_reason = "Покупка" >
    <gift_name>Благодарим!</gift_name>
  </gift>
  <contacts id="С10">
    <location id="Л10">
      <country>България</country>
      <city>Бургас</city>
      <street>Сезам</street>
      <building_number>5789</building_number>
    </location>
    <phone>08765432</phone>
    <website>Свежо-Утро.кафе</website>
    <e-mail>Свежо@Утро</e-mail>
  </contacts>
  <employees>
    <employee id="E100" position="Продавач" sex="Мъж">
      <emp_name>Валери</emp_name>
      <salary>700</salary>
      <age>80</age>
    </employee>
    <employee id="E101" position="Готвач" sex="Мъж">
      <emp_name>Гошо</emp_name>
      <salary>600</salary>
      <age>45</age>
    </employee>
    <employee id="E102" position="Управител" sex="Жена">
      <emp_name>Миленка</emp_name>
      <salary>1200</salary>
      <age>54</age>
    </employee>
    <employee id="E103" position="Чистач" sex="Жена">
      <emp_name>Глория</emp_name>
      <salary>1650</salary>
      <age>45</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_9.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="9">
    <name>Ред кафе</name>
    <working_time>от 7:00 - до 20:00</working_time>
    <products>
        <product id="п90">
            <price>2.50лв</price>
            <product_name>бисквити</product_name>
            <description>най-яките бисквити!</description>
            <food id="Ф900" food_type="Солено">
              <food_name>биквити с шоколад</food_name>
            </food>
            <food id="Ф91" food_type="Солено">
              <food_name>биквити с бял шоколад</food_name>
            </food>
            <food id="Ф902" food_type="Солено">
              <food_name>пълнозърнести бисквити</food_name>
            </food>
        </product>
        <product id="п91">
            <price>2лв</price>
            <product_name>кафе</product_name>
            <description>най-яките кафета! Традиционни</description>
            <coffee id="к910"  supplement_type="Захар" drink_type="Гореща">
              <coffee_name>Lavazza</coffee_name>
                <coffee_type>Горещо</coffee_type>
                <supplement_price>0.5лв</supplement_price>
            </coffee>
            <coffee id="к912"  supplement_type="Захар" drink_type="Гореща">
              <coffee_name>Cararro</coffee_name>
                <coffee_type>Горещо</coffee_type>
                <supplement_price>0.5лв</supplement_price>
            </coffee>
        </product>
    </products>
    <contacts id="С9">
        <location id="Л9">
            <country>България</country>
            <city>София</city>
            <street>Атанас Далчев</street>
            <building_number>ГР76</building_number>
        </location>
        <phone>0887347690</phone>
        <website>Редкафе.бг</website>
        <e-mail>Редкафе@кафе.ком</e-mail>
    </contacts>
    <employees>
        <employee id="Е90" position="Продавач" sex="Мъж">
            <emp_name>Лейла</emp_name>
            <salary>900</salary>
            <age>23</age>
        </employee>
        <employee id="Е91" position="Продавач" sex="Мъж">
            <emp_name>Кайла</emp_name>
            <salary>900</salary>
            <age>67</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_6.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="6">
    <name>Тракйската принцеса</name>
    <working_time>от 7:00 - до 6:00</working_time>
    <products>
        <product id="п61">
            <price>5.50лв.</price>
            <product_name>Палачинки</product_name>
            <description>
			Че палачинките са любима закуска на малки и големи няма никакъв спор. 
                    Сигурно на пръсти се броят хората, които не ги обичат.
                    Със сиренце, сладко, конфитюр, шоколад, кашкавал или каквото там обичате,
                    те са вкусни, мекички, наслада за небцето и сетивата.
			</description>
            <food id="X610" food_type="Солено">
              <food_name>Палачинки с плодове</food_name>
            </food>
            <food id="X611" food_type="Солено">
              <food_name>Палачинки със сирене</food_name>
            </food>
			<food id="X612" food_type="Солено">
              <food_name>Палачинки с шунка и кашкавал</food_name>
            </food>
			<food id="X614" food_type="Солено">
              <food_name>Палачинки с шунка и топено сирене</food_name>
            </food>
            <food id="X615" food_type="Солено">
              <food_name>Палачинки с шоколад</food_name>
            </food>
            <food id="X616" food_type="Солено">
              <food_name>Палачинки със сладко</food_name>
            </food>
        </product>
        <product id="п611">
            <price>2лв</price>
            <product_name>кафе</product_name>
            <description>най-яките кафета! Традиционни</description>
            <coffee id="к6110" >
                <coffee_name>Lavazza</coffee_name>
                <coffee_type>Горещо</coffee_type>
                <supplement_price>0.10лв</supplement_price>
            </coffee>
            <coffee id="к6111"  supplement_type="Сметана" drink_type="Гореща">
                <coffee_name>Cararro</coffee_name>
                <coffee_type>Горещо</coffee_type>
                <supplement_price>0.40лв</supplement_price>
            </coffee>
        </product>
    </products>
    <contacts id="С6">
        <location id="Л6">
            <country>България</country>
            <city>София</city>
            <street>Граф Игнатиев</street>
            <building_number>7640</building_number>
        </location>
        <phone>0887347690</phone>
        <website>ТракйскатаПринцеса.бг</website>
        <e-mail>ТракйскатаПринцеса@кафе.ком</e-mail>
    </contacts>
    <employees>
        <employee id="Е60" position="Продавач" sex="Мъж">
            <emp_name>Симона</emp_name>
            <salary>980</salary>
            <age>23</age>
        </employee>
        <employee id="Е61" position="Продавач" sex="Мъж">
            <emp_name>Кайла-Боро</emp_name>
            <salary>943</salary>
            <age>67</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_20.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="20">
  <name>Сити</name>
  <working_time>от 6 до 20</working_time>
  <products>
    <product id="П200">
      <price>6лв</price>
      <product_name>Фреш меню</product_name>
      <coffee id="C2000" supplement_type="Без" drink_type="Студена">
        <coffee_name>Фрапе</coffee_name>
        <coffee_type>Сити Класик</coffee_type>
      </coffee>
      <food id="Х2001" food_type="Сладко">
        <food_name>Плодова салата</food_name>
      </food>
    </product>
    <product id="П201">
      <price>6лв</price>
      <product_name>Сладко меню</product_name>
      <coffee id="C2010" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Късо или дълго кафе</coffee_name>
        <coffee_type>Сити Класик</coffee_type>
      </coffee>
      <food id="Х2011" food_type="Сладко">
        <food_name>Кексче</food_name>
      </food>
    </product>
    <product id="П202">
      <price>2лв</price>
      <product_name>Кафе</product_name>
      <coffee id="К2020" supplement_type="Без" drink_type="Гореща">
        <coffee_name>класическо кафе</coffee_name>
        <coffee_type>Сити Класик</coffee_type>
      </coffee>
      <coffee id="К2021" supplement_type="Мляко" drink_type="Гореща">
        <coffee_name>Американо</coffee_name>
        <coffee_type>Сити Амер</coffee_type>
        <supplement_price>1лв</supplement_price>
      </coffee>
      <coffee id="К2022" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Капучино</coffee_name>
        <coffee_type>Сити Амер</coffee_type>
      </coffee>
      <coffee id="К2023" supplement_type="Без" drink_type="Студена">
        <coffee_name>Лате</coffee_name>
        <coffee_type>Сити Амер</coffee_type>
      </coffee>
    </product>
  </products>
  <gift id="Г20" gift_reason="Покупка" gift_type="Отстъпка">
    <gift_name>Заповядайте отново</gift_name>
  </gift>
  <contacts id="С20">
    <location id="Л20">
      <country>България</country>
      <city>Пловдив</city>
      <building_number>7654</building_number>
    </location>
    <phone>08846364</phone>
    <website>Сити-кафе.ком</website>
    <e-mail>Сити@кафе.ком</e-mail>
  </contacts>
  <employees>
    <employee id="E200" position="Управител" sex="Мъж">
      <emp_name>Иван</emp_name>
      <salary>800</salary>
    </employee>
    <employee id="E201" position="Продавач" sex="Жена">
      <emp_name>Мария</emp_name>
      <salary>700</salary>
    </employee>
    <employee id="E202" position="Чистач" sex="Мъж">
      <emp_name>Терас</emp_name>
      <salary>600</salary>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="1">
    <name>Най-яката къща за кафе бадка!</name>
    <working_time>от 7:00 - до 20:00</working_time>
    <products>
        <product id="п0201">
            <price>5.00</price>
            <product_name>Палачинки</product_name>
            <description>
			Че палачинките са любима закуска на малки и големи няма никакъв спор. 
                    Сигурно на пръсти се броят хората, които не ги обичат.
                    Със сиренце, сладко, конфитюр, шоколад, кашкавал или каквото там обичате,
                    те са вкусни, мекички, наслада за небцето и сетивата.
			</description>
            <food id="X201" food_type="Солено">
              <food_name>Палачинки с плодове</food_name>
            </food>
            <food id="X202" food_type="Солено">
              <food_name>Палачинки със сирене</food_name>
            </food>
			<food id="X203" food_type="Солено">
              <food_name>Палачинки с шунка и кашкавал</food_name>
            </food>
			<food id="X204" food_type="Солено">
              <food_name>Палачинки с шунка и топено сирене</food_name>
            </food>
            <food id="X205" food_type="Солено">
              <food_name>Палачинки с шоколад</food_name>
            </food>
            <food id="X206" food_type="Солено">
              <food_name>Палачинки със сладко</food_name>
            </food>
        </product>
        <product id="п1">
            <price>2лв</price>
            <product_name>кафе</product_name>
            <description>най-яките кафета! Традиционни</description>
            <coffee id="к201">
              <coffee_name>Lavazza</coffee_name>
              <coffee_type>Горещо</coffee_type>
              <supplement_price>0лв</supplement_price>
            </coffee>
            <coffee id="к202">
              <coffee_name>Cararro</coffee_name>
              <coffee_type>Горещо</coffee_type>
              <supplement_price>0лв</supplement_price>
            </coffee>
        </product>
    </products>
    <contacts id="а1.0">
        <location id="а1.1">
            <country>България</country>
            <city>София</city>
            <street>Граф Игнатиев</street>
            <building_number>7864</building_number>
        </location>
        <phone>0887347690</phone>
        <website>www.кафетата.bg</website>
        <e-mail>best_coffee@coffee.com</e-mail>
    </contacts>
    <employees>
        <employee id="с1.0" position="Продавач" sex="Мъж">
            <emp_name>Лейла</emp_name>
            <salary>900</salary>
            <age>23</age>
        </employee>
        <employee id="с1.1" position="Продавач" sex="Мъж">
            <emp_name>Кайла</emp_name>
            <salary>900</salary>
            <age>67</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_18.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="18">
  <name>Черен рай</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П180">
      <price>3лв</price>
      <product_name>Шарени кафета</product_name>
      <coffee id="К1801" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Капучино малина</coffee_name>
        <coffee_type>Лаваца</coffee_type>
      </coffee>
      <coffee id="К1802" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Капучино лешник</coffee_name>
        <coffee_type>Лаваца</coffee_type>
      </coffee>
      <coffee id="К1803" supplement_type="Захар" drink_type="Гореща">
        <coffee_name>Дълго кафе с портокал</coffee_name>
        <coffee_type>Лаваца</coffee_type>
        <supplement_price>0.40лв</supplement_price>
      </coffee>
    </product>
  </products>
  <contacts id="С180">
    <location id="Л180">
      <country>Ромъния</country>
      <city>Брашов</city>
      <street>Хеог</street>
      <building_number>т45</building_number>
    </location>
    <phone>08765432</phone>
    <website>Черен - рай.ро</website>
    <e-mail>Черен@рай</e-mail>
  </contacts>
  <employees>
    <employee id="E180" position="Продавач" sex="Мъж">
      <emp_name>Мариан</emp_name>
      <salary>606</salary>
      <age>30</age>
    </employee>
    <employee id="E181" position="Продавач" sex="Жена">
      <emp_name>Мария</emp_name>
      <salary>987</salary>
      <age>43</age>
    </employee>
    <employee id="E182" position="Продавач" sex="Жена">
      <emp_name>Мирослава</emp_name>
      <salary>835</salary>
      <age>30</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_13.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="13">
  <name>Све</name>
  <working_time>от 6 до 20</working_time>
  <products>
    <product id="П130">
      <price>4лв.</price>
      <product_name>Натурални Кафета</product_name>
      <coffee id="К130" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Късо кафе</coffee_name>
        <coffee_type>Све</coffee_type>
      </coffee>
      <coffee id="К131" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Безкофеиново</coffee_name>
        <coffee_type>Све</coffee_type>
      </coffee>
      <coffee id="К132" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Све</coffee_type>
      </coffee>
    </product>
    <product id="П131">
      <price>4лв.</price>
      <product_name>Кафета с аромати</product_name>
      <coffee id="К133" supplement_type="Мляко" drink_type="Студена">
        <coffee_name>Лате боровинка</coffee_name>
        <coffee_type>Све</coffee_type>
        <supplement_price>1</supplement_price>
      </coffee>
      <coffee id="К134" supplement_type="Мляко" drink_type="Гореща">
        <coffee_name>Еспресо лешник</coffee_name>
        <coffee_type>Све</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
      <coffee id="К135" supplement_type="Мляко" drink_type="Гореща">
        <coffee_name>Макиато портокал</coffee_name>
        <coffee_type>Све</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
    </product>
  </products>
  <contacts id="Л13">
    <location id="C13">
      <country>България</country>
      <city>Златни пясъци</city>
      <building_number>443</building_number>
    </location>
    <phone>08765432</phone>
    <website>Све.ком</website>
    <e-mail>Све@кафе</e-mail>
  </contacts>
  <employees>
    <employee id="E130" position="Продавач" sex="Мъж">
      <emp_name>Михаил</emp_name>
      <salary>800</salary>
      <age>30</age>
    </employee>
    <employee id="E131" position="Готвач" sex="Жена">
      <emp_name>Петър</emp_name>
      <salary>1000</salary>
      <age>34</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_16.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="16">
  <name>Стар Бъкс</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П160">
      <price>4</price>
      <product_name>Кафета</product_name>
      <coffee id="К160" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Лате малина</coffee_name>
        <coffee_type>Стар</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К161" supplement_type="Сметана" drink_type="Студена">
        <coffee_name>Шейк праскова</coffee_name>
        <coffee_type>Стар</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К162" supplement_type="Сметана" drink_type="Студена">
        <coffee_name>Шейк шоколад</coffee_name>
        <coffee_type>Стар</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К163" supplement_type="Захар" drink_type="Студена">
        <coffee_name>Капучино тиква</coffee_name>
        <coffee_type>Стар</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К164" supplement_type="Захар" drink_type="Студена">
        <coffee_name>Лате кокос</coffee_name>
        <coffee_type>Стар</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
    </product>
    <product id="П161">
      <price>6</price>
      <product_name>Сандвич</product_name>
      <food id="Х160" food_type="Солено">
        <food_name>Сандвич с шунка</food_name>
      </food>
      <food id="Х161" food_type="Солено">
        <food_name>Сандвич с кашкавал</food_name>
      </food>
      <food id="Х162" food_type="Сладко">
        <food_name>Сандвич с плодове</food_name>
      </food>
    </product>
  </products>
  <contacts id="L2">
    <location id="C2">
      <country>България</country>
      <city>Варна</city>
      <street>Хеог</street>
      <building_number>3424</building_number>
    </location>
    <phone>08765432</phone>
    <website>Стар-бъкс.ком</website>
    <e-mail>Стар@бъксс</e-mail>
  </contacts>
  <employees>
    <employee id="E160" position="Продавач" sex="Мъж">
      <emp_name>Георги</emp_name>
      <salary>800</salary>
      <age>30</age>
    </employee>
    <employee id="E161" position="Продавач" sex="Жена">
      <emp_name>Стоян</emp_name>
      <salary>800</salary>
      <age>34</age>
    </employee>
  </employees>
</CoffeeHouse>
