=== biannka/ASP_NET/XmlSample/App_Data/coffeeHouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CoffeeHouse">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="working_time"/>
        <xs:element ref="products"/>
        <xs:element minOccurs="0" ref="gift"/>
        <xs:element ref="contacts"/>
        <xs:element ref="employees"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.CoffeeHouse"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.CoffeeHouse">
    <xs:attribute name="id" use="required"/>
  </xs:attributeGroup>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="working_time" type="xs:string"/>
  <xs:element name="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="product"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="price"/>
        <xs:element ref="product_name"/>
        <xs:element minOccurs="0" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="coffee"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="food"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="image"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.product"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.product">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="image" type="xs:string"/>
  <xs:element name="price" type="xs:string"/>
  <xs:element name="product_name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="coffee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coffee_name"/>
        <xs:element ref="coffee_type"/>
        <xs:element minOccurs="0" ref="supplement_price"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.coffee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.coffee">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="drink_type" default="Гореща">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Гореща"/>
          <xs:enumeration value="Студена"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="supplement_type" default="Без">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Захар"/>
          <xs:enumeration value="Канела"/>
          <xs:enumeration value="Мляко"/>
          <xs:enumeration value="Сметана"/>
          <xs:enumeration value="Без"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="coffee_type" type="xs:string"/>
  <xs:element name="coffee_name" type="xs:string"/>
  <xs:element name="supplement_price" type="xs:string"/>
  <xs:element name="food">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="food_name">
          <xs:attributeGroup ref="attlist.food"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.food">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="food_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Солено"/>
          <xs:enumeration value="Сладко"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="food_name">
    <xs:sequence>
      <xs:element ref="food_name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="food_name" type="xs:string"/>
  <xs:element name="gift">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="gift_name">
          <xs:attributeGroup ref="attlist.gift"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.gift">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="gift_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Храна"/>
          <xs:enumeration value="Кафе"/>
          <xs:enumeration value="Отстъпка"/>
          <xs:enumeration value="Ваучер"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="gift_reason" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Редовен"/>
          <xs:enumeration value="Покупка"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="gift_name">
    <xs:sequence>
      <xs:element ref="gift_name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="gift_name" type="xs:string"/>
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location"/>
        <xs:element ref="phone"/>
        <xs:element ref="website"/>
        <xs:element ref="e-mail"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.contacts"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.contacts">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="phone" type="xs:string"/>
  <xs:element name="e-mail" type="xs:string"/>
  <xs:element name="website" type="xs:string"/>
  <xs:element name="location">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="country"/>
        <xs:element ref="city"/>
        <xs:element minOccurs="0" ref="street"/>
        <xs:element ref="building_number"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="country" type="xs:string"/>
  <xs:element name="city" type="xs:string"/>
  <xs:element name="street" type="xs:string"/>
  <xs:element name="building_number" type="xs:string"/>
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="employee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="emp_name"/>
        <xs:element ref="salary"/>
        <xs:element minOccurs="0" ref="age"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.employee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.employee">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="position" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Продавач"/>
          <xs:enumeration value="Готвач"/>
          <xs:enumeration value="Чистач"/>
          <xs:enumeration value="Управител"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="sex" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Мъж"/>
          <xs:enumeration value="Жена"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="emp_name" type="xs:string"/>
  <xs:element name="salary" type="xs:string"/>
  <xs:element name="age" type="xs:string"/>
</xs:schema>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_11.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="11">
    <name>Коста Кафе</name>
    <working_time>от 10 до 10</working_time>
    <products>
        <product id="П110">
            <price>5лв.</price>
            <product_name>Чаша</product_name>
        </product>
        <product id="П111">
            <price>10лв.</price>
            <product_name>Уред за френско кафе</product_name>
        </product>
    </products>
    <contacts id="С11">
        <location id="Л11">
            <city>София</city>
            <building_number>4</building_number>
        </location>
        <phone>89557</phone>
        <website>Коста.ком</website>
        <e-mail>Коста@кафе</e-mail>
    </contacts>
    <employees>
        <employee id="е110" position="Готвач" sex="Жена">
            <emp_name>Михаела</emp_name>
            <salary>700</salary>
        </employee>
        <employee id="e112" position="Продавач" sex="Мъж">
            <emp_name>Пламен</emp_name>
            <salary>700</salary>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_11.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="ID1">
    <name>Коста Кафе</name>
    <working_time>от 10 до 10</working_time>
    <products>
        <product id="ID1">
            <price>5</price>
            <product_name>Чаша</product_name>
        </product>
        <product id="ID2">
            <price>10</price>
            <product_name>Уред за френско кафе</product_name>
        </product>
    </products>
    <contacts id="IDc1">
        <location id="IDl1">
            <city>София</city>
            <building_number>4</building_number>
        </location>
        <phone>89557</phone>
        <website>Коста.ком</website>
        <e-mail>Коста@кафе</e-mail>
    </contacts>
    <employees>
        <employee id="IDe1" position="Готвач" sex="Жена">
            <emp_name>Михаела</emp_name>
            <salary>700</salary>
        </employee>
        <employee id="IDe2" position="Продавач" sex="Мъж">
            <emp_name>Пламен</emp_name>
            <salary>700</salary>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_0.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="0">
  <name>Фреш Кафе</name>
  <working_time>От 6 до 16 часа</working_time>
  <products>
    <product id="П1">
      <price>5лв</price>
      <product_name>Млечна закуска</product_name>
      <coffee id="К00" supplement_type="Без" drink_type="Студена">
        <coffee_name>Лате</coffee_name>
        <coffee_type>Грийн Метх</coffee_type>
      </coffee>
      <food id="Хр01" food_type="Сладко">
        <food_name>Мюсли с пресни плодове</food_name>
      </food>
    </product>
    <product id="П2">
      <price>6лв.</price>
      <product_name>Пълнозърнеста закуска</product_name>
      <coffee id="К20" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Грийн Лип</coffee_type>
      </coffee>
      <food id="Х21" food_type="Сладко">
        <food_name>Пълнозърнеста бисквита</food_name>
      </food>
    </product>
    <product id="П3">
      <price>6</price>
      <product_name>Голяма закуска</product_name>
      <coffee id="К30" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Дълго кафе с портокал</coffee_name>
        <coffee_type>Грийн Мих</coffee_type>
      </coffee>
      <food id="Х31" food_type="Солено">
        <food_name>Сандвич с пълнозурнест хляб</food_name>
      </food>
    </product>
  </products>
  <gift id="Г0" gift_reason="Покупка" gift_type="Отстъпка">
    <gift_name>Бонус</gift_name>
  </gift>
  <contacts id="С0">
    <location id="Л0">
      <country>Сърбия</country>
      <city>Белград</city>
      <street>Белида</street>
      <building_number>8989</building_number>
    </location>
    <phone>0889 679 212</phone>
    <website>Фреш - кафе.ком</website>
    <e-mail>Фреш@кафе.ком</e-mail>
  </contacts>
  <employees>
    <employee id="E0" position="Продавач" sex="Жена">
      <emp_name>Малина</emp_name>
      <salary>600</salary>
      <age>29</age>
    </employee>
    <employee id="E1" position="Управител" sex="Жена">
      <emp_name>Марияна</emp_name>
      <salary>100</salary>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_14.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="14">
  <name>Златни</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П140">
      <price>4лв.</price>
      <product_name>Кафета</product_name>
      <coffee id="К140" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Късо кафе</coffee_name>
        <coffee_type>Мока</coffee_type>
      </coffee>
      <coffee id="К141" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Мока</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К142" supplement_type="Мляко" drink_type="Гореща">
        <coffee_name>Мокачино банан</coffee_name>
        <coffee_type>Мока</coffee_type>
        <supplement_price>0.50лв.</supplement_price>
      </coffee>
      <coffee id="К143" supplement_type="Мляко" drink_type="Гореща">
        <coffee_name>Мокачино портокал</coffee_name>
        <coffee_type>Мока</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
    </product>
    <product id="П141">
      <price>4лв.</price>
      <product_name>Свежи кафета</product_name>
    <coffee id="К144" supplement_type="Мляко" drink_type="Студена">
        <coffee_name>Мокачино плод</coffee_name>
        <coffee_type>Мока</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
    </product>
  </products>
  <contacts id="Л14">
    <location id="C14">
      <country>България</country>
      <city>Златни пясъци</city>
      <building_number>654</building_number>
    </location>
    <phone>08765432</phone>
    <website>Златни.ком</website>
    <e-mail>Златни@кафе</e-mail>
  </contacts>
  <employees>
    <employee id="E140" position="Продавач" sex="Мъж">
      <emp_name>Михаил</emp_name>
      <salary>800</salary>
      <age>30</age>
    </employee>
    <employee id="E141" position="Готвач" sex="Жена">
      <emp_name>Петър</emp_name>
      <salary>1000</salary>
      <age>34</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_19.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="1">
    <name>Най-яката къща за кафе бадка!</name>
    <working_time>от 7:00 - до 20:00</working_time>
    <products>
        <product id="п200">
            <price>5.00</price>
            <product_name>Кроасани</product_name>
            <description>
			Ръчно приготвени по оригинални рецепти на, пресни и сочни всеки ден, 
                    за възможно най-добрия старт на деня в комбинация с хубаво кафе!
			</description>
            <food id="X201" food_type="Солено">
              <food_name>Кроасан с плодове</food_name>
            </food>
            <food id="X202" food_type="Солено">
              <food_name>Кроасан със сирене</food_name>
            </food>
			<food id="X203" food_type="Солено">
              <food_name>Кроасан с шунка и кашкавал</food_name>
            </food>
			<food id="X204" food_type="Солено">
              <food_name>Кроасан с шунка и топено сирене</food_name>
            </food>
            <food id="X205" food_type="Солено">
              <food_name>Кроасан с шоколад</food_name>
            </food>
            <food id="X206" food_type="Солено">
              <food_name>Кроасан със сладко</food_name>
            </food>
            <food id="X207" food_type="Солено">
              <food_name>Кроасан с масло</food_name>
            </food>
        </product>
        <product id="п201">
            <price>2лв</price>
            <product_name>Kафе</product_name>
            <description>най-яките кафета! Традиционни</description>
          <coffee id="к190" drink_type ="Гореща" supplement_type = "Сметана">
              <coffee_name>Виенско кафе</coffee_name>
              <coffee_type>Cararro</coffee_type>
              <supplement_price>0лв</supplement_price>
            </coffee>
          <coffee id="к191" drink_type ="Гореща" supplement_type = "Канела">
              <coffee_name>Капучно с канела</coffee_name>
              <coffee_type>Cararro</coffee_type>
              <supplement_price>0лв</supplement_price>
            </coffee>
        </product>
    </products>
    <contacts id="c20">
        <location id="l20">
            <country>България</country>
            <city>София</city>
            <street>Граф Игнатиев</street>
            <building_number>7864</building_number>
        </location>
        <phone>0887347690</phone>
        <website>www.кафетата.bg</website>
        <e-mail>best_coffee@coffee.com</e-mail>
    </contacts>
    <employees>
        <employee id="e200" position="Продавач" sex="Мъж">
            <emp_name>Димитър</emp_name>
            <salary>900</salary>
            <age>23</age>
        </employee>
        <employee id="e201" position="Продавач" sex="Мъж">
            <emp_name>Кайла</emp_name>
            <salary>900</salary>
            <age>67</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_5.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id = "5">
    <name>Кафе неща</name>
    <working_time>От 06.00 до 20.00. Всеки ден</working_time>
    <products>
        <product id="П500">
            <price>5лв</price>
            <product_name>Чаша</product_name>
            <description>
                Голяма и удобна. Ще запази топлината на кафето!
            </description>
            <image>cup1.jpg</image>
        </product>
        <product id="П501">
            <price>7лв</price>
            <product_name>Термус</product_name>
            <description>
                Ние всички сме много заети, но винаги има време за кафе! 
                Една кафе напитка е нещо, на което може да се насладите навсякъде. 
                Термусът е най-подходящ продукт, който ще я запази гореща и освежаваща докато пътувате.
            </description>
            <image>cup2.jpg</image>
        </product>
    </products>
    <contacts id="С05">
        <location id="Л05">
            <country>България</country>
            <city>София</city>
            <street>Студентски град</street>
            <building_number>ХЪ432</building_number>
        </location>
        <phone>0888 543 093</phone>
        <website>КафеНеща.ком</website>
        <e-mail>Кафенеща@емейл.ком</e-mail>
    </contacts>
    <employees>
        <employee id="Е51" position="Управител" sex="Мъж">
            <emp_name>Петко Йорданов</emp_name>
            <salary>1000</salary>
            <age>26</age>
        </employee>
        <employee id="Е52" position="Продавач" sex="Жена">
            <emp_name>Гергана Маринова</emp_name>
            <salary>1000</salary>
            <age>35</age>
        </employee>
        <employee id="Е53" position="Продавач" sex="Мъж">
            <emp_name>Петър Иванов</emp_name>
            <salary>1000</salary>
            <age>26</age>
        </employee>
        <employee id="Е54" position="Продавач" sex="Жена">
            <emp_name>Симона Владимирова</emp_name>
            <salary>1000</salary>
            <age>26</age>
        </employee>
        <employee id="Е65" position="Готвач" sex="Мъж">
            <emp_name>Димитър Ангелов</emp_name>
            <salary>1000</salary>
            <age>26</age>
        </employee>
        <employee id="Е66" position="Готвач" sex="Мъж">
            <emp_name>Георги Колев</emp_name>
            <salary>1000</salary>
            <age>26</age>
        </employee>
        <employee id="Е67" position="Чистач" sex="Жена">
            <emp_name>Мария Трайкова</emp_name>
            <salary>800</salary>
            <age>35</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_12.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="12">
  <name>Сири</name>
  <working_time>от 6 до 20</working_time>
  <products>
    <product id="П120">
      <price>4лв.</price>
      <product_name>Класически Кафета</product_name>
      <coffee id="К120" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Късо кафе</coffee_name>
        <coffee_type>Сири</coffee_type>
      </coffee>
      <coffee id="К121" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Безкофеиново</coffee_name>
        <coffee_type>Сири</coffee_type>
      </coffee>
      <coffee id="К122" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Сири</coffee_type>
      </coffee>
    </product>
    <product id="П121">
      <price>4лв.</price>
      <product_name>Кафета с вкусове</product_name>
    <coffee id="К123" supplement_type="Мляко" drink_type="Студена">
        <coffee_name>Лате макиато малина</coffee_name>
        <coffee_type>Сири</coffee_type>
        <supplement_price>0.5лв.</supplement_price>
      </coffee>
      <coffee id="К124" supplement_type="Мляко" drink_type="Студена">
        <coffee_name>Лате макиато праскова</coffee_name>
        <coffee_type>Сири</coffee_type>
        <supplement_price>0.5лв.</supplement_price>
      </coffee>
      <coffee id="К125" supplement_type="Мляко" drink_type="Студена">
        <coffee_name>Лате макиато ягода</coffee_name>
        <coffee_type>Сири</coffee_type>
        <supplement_price>0.5лв.</supplement_price>
      </coffee>
    </product>
  </products>
  <contacts id="Л12">
    <location id="C12">
      <country>България</country>
      <city>Враца</city>
      <building_number>64</building_number>
    </location>
    <phone>08765432</phone>
    <website>Сири.ком</website>
    <e-mail>Сири@кафе</e-mail>
  </contacts>
  <employees>
    <employee id="E120" position="Продавач" sex="Мъж">
      <emp_name>Констатин</emp_name>
      <salary>800</salary>
      <age>30</age>
    </employee>
    <employee id="E121" position="Продавач" sex="Мъж">
      <emp_name>Илиян</emp_name>
      <salary>800</salary>
      <age>34</age>
    </employee>
    <employee id="E122" position="Управител" sex="Жена">
      <emp_name>Александра</emp_name>
      <salary>1000</salary>
      <age>34</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_9.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="1">
    <name>Най-яката къща за кафе бадка!</name>
    <working_time>от 7:00 - до 20:00</working_time>
    <products>
        <product id="п10">
            <price>2.50лв</price>
            <product_name>биквити</product_name>
            <description>най-яките бисквити!</description>
            <food id="Ф1000" food_type="Солено">
              <food_name>биквити с шоколад</food_name>
            </food>
            <food id="Ф1001" food_type="Солено">
              <food_name>биквити с бял шоколад</food_name>
            </food>
            <food id="Ф1002" food_type="Солено">
              <food_name>пълнозърнести бисквити</food_name>
            </food>
        </product>
        <product id="п11">
            <price>2лв</price>
            <product_name>кафе</product_name>
            <description>най-яките кафета! Традиционни</description>
            <coffee id="к1.0">
              <coffee_name>Lavazza</coffee_name>
              <coffee_type>Горещо</coffee_type>
              <supplement_price>0лв</supplement_price>
            </coffee>
            <coffee id="к1.1">
              <coffee_name>Cararro</coffee_name>
              <coffee_type>Горещо</coffee_type>
              <supplement_price>0лв</supplement_price>
            </coffee>
        </product>
    </products>
    <contacts id="а1.0">
        <location id="а1.1">
            <country>България</country>
            <city>София</city>
            <street>Граф Игнатиев</street>
            <building_number>7864</building_number>
        </location>
        <phone>0887347690</phone>
        <website>www.кафетата.bg</website>
        <e-mail>best_coffee@coffee.com</e-mail>
    </contacts>
    <employees>
        <employee id="с1.0" position="Продавач" sex="Мъж">
            <emp_name>Лейла</emp_name>
            <salary>900</salary>
            <age>23</age>
        </employee>
        <employee id="с1.1" position="Продавач" sex="Мъж">
            <emp_name>Кайла</emp_name>
            <salary>900</salary>
            <age>67</age>
        </employee>
    </employees>
</CoffeeHouse>
