=== biannka/ASP_NET/XmlSample/App_Data/coffeeHouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CoffeeHouse">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="working_time"/>
        <xs:element ref="products"/>
        <xs:element minOccurs="0" ref="gift"/>
        <xs:element ref="contacts"/>
        <xs:element ref="employees"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.CoffeeHouse"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.CoffeeHouse">
    <xs:attribute name="id" use="required"/>
  </xs:attributeGroup>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="working_time" type="xs:string"/>
  <xs:element name="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="product"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="price"/>
        <xs:element ref="product_name"/>
        <xs:element minOccurs="0" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="coffee"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="food"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="image"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.product"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.product">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="image" type="xs:string"/>
  <xs:element name="price" type="xs:string"/>
  <xs:element name="product_name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="coffee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coffee_name"/>
        <xs:element ref="coffee_type"/>
        <xs:element minOccurs="0" ref="supplement_price"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.coffee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.coffee">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="drink_type" default="Гореща">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Гореща"/>
          <xs:enumeration value="Студена"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="supplement_type" default="Без">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Захар"/>
          <xs:enumeration value="Канела"/>
          <xs:enumeration value="Мляко"/>
          <xs:enumeration value="Сметана"/>
          <xs:enumeration value="Без"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="coffee_type" type="xs:string"/>
  <xs:element name="coffee_name" type="xs:string"/>
  <xs:element name="supplement_price" type="xs:string"/>
  <xs:element name="food">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="food_name">
          <xs:attributeGroup ref="attlist.food"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.food">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="food_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Солено"/>
          <xs:enumeration value="Сладко"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="food_name">
    <xs:sequence>
      <xs:element ref="food_name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="food_name" type="xs:string"/>
  <xs:element name="gift">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="gift_name">
          <xs:attributeGroup ref="attlist.gift"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.gift">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="gift_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Храна"/>
          <xs:enumeration value="Кафе"/>
          <xs:enumeration value="Отстъпка"/>
          <xs:enumeration value="Ваучер"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="gift_reason" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Редовен"/>
          <xs:enumeration value="Покупка"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="gift_name">
    <xs:sequence>
      <xs:element ref="gift_name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="gift_name" type="xs:string"/>
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location"/>
        <xs:element ref="phone"/>
        <xs:element ref="website"/>
        <xs:element ref="e-mail"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.contacts"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.contacts">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="phone" type="xs:string"/>
  <xs:element name="e-mail" type="xs:string"/>
  <xs:element name="website" type="xs:string"/>
  <xs:element name="location">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="country"/>
        <xs:element ref="city"/>
        <xs:element minOccurs="0" ref="street"/>
        <xs:element ref="building_number"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="country" type="xs:string"/>
  <xs:element name="city" type="xs:string"/>
  <xs:element name="street" type="xs:string"/>
  <xs:element name="building_number" type="xs:string"/>
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="employee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="emp_name"/>
        <xs:element ref="salary"/>
        <xs:element minOccurs="0" ref="age"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.employee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.employee">
    <xs:attribute name="id" use="required" type="xs:ID"/>
    <xs:attribute name="position" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Продавач"/>
          <xs:enumeration value="Готвач"/>
          <xs:enumeration value="Чистач"/>
          <xs:enumeration value="Управител"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="sex" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Мъж"/>
          <xs:enumeration value="Жена"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="emp_name" type="xs:string"/>
  <xs:element name="salary" type="xs:string"/>
  <xs:element name="age" type="xs:string"/>
</xs:schema>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_8.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="8">
  <name>Лед кафе</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П80">
      <price>4лв.</price>
      <product_name>Студени кафета</product_name>
      <coffee id="Cвс4е30" supplement_type="Без" drink_type="Студена">
        <coffee_name>Лате малина</coffee_name>
        <coffee_type>Нескафе</coffee_type>
      </coffee>
      <coffee id="К801" supplement_type="Без" drink_type="Студена">
        <coffee_name>Лате ягода</coffee_name>
        <coffee_type>Нескафе</coffee_type>
      </coffee>
      <coffee id="К802" supplement_type="Захар" drink_type="Студена">
        <coffee_name>Фрапе</coffee_name>
        <coffee_type>Нескафе</coffee_type>
        <supplement_price>0.5лв</supplement_price>
      </coffee>
    </product>
    <product id="П81">
      <price>6лв.</price>
      <product_name>Сладолед</product_name>
      <food id="Х810" food_type="Сладко">
        <food_name>Сладолед горски плод на клечка</food_name>
      </food>
      <food id="Х811" food_type="Сладко">
        <food_name>Шоколадова фантазия</food_name>
      </food>
      <food id="Х812" food_type="Сладко">
        <food_name>Сладолед ванилия на клечка</food_name>
      </food>
    </product>
  </products>
  <contacts id="C8">
    <location id="Л8">
      <country>България</country>
      <city>Варна</city>
      <street>Хеог</street>
      <building_number>3424</building_number>
    </location>
    <phone>08765432</phone>
    <website>Лед-кафе.ком</website>
    <e-mail>Лед@кафе</e-mail>
  </contacts>
  <employees>
    <employee id="E80" position="Продавач" sex="Мъж">
      <emp_name>Силвестър</emp_name>
      <salary>600</salary>
      <age>30</age>
    </employee>
    <employee id="E81" position="Продавач" sex="Жена">
      <emp_name>Тошка</emp_name>
      <salary>983</salary>
      <age>32</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_4.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id = "4">
    <name>Черни Зърна</name>
    <working_time>От 06.00 до 20.00. Всеки ден</working_time>
    <products>
        <product id="П400">
            <price>100лв.</price>
            <product_name>Кафемашина</product_name>
            <description>
                За да се уверите, че винаги ще получите същото високо качество , с чудесен вкус, независимо дали сте у дома или навън. 
                Уверете се в лекотата на използване на Tassimo машината.
                Той върши цялата техническа , сложна работа , така че всичко, което трябва да направите е да натиснете един бутон!
                Можете да получавате всеки ден у дома перфектната чаша кафе!
            </description>
        </product>
        <product id="П401">
            <price>30лв</price>
            <product_name>Машина за фрапе</product_name>
        </product>
        <product id="П402">
            <price>10лв.</price>
            <product_name>Френска преса</product_name>
            <description>
                Френската преса е един от най-старите и удобни начини за приготвяне на кафе.
                С нея се работи лесно, не е скъпа и прави наистина добро кафе. 
                Още ли търсите начин да приготвите кафе със силен аромат, плътно тяло и наситен вкус? 
                Току що го открихте – незаменимата френска преса.
            </description>
        </product>
    </products>
    <contacts id="С400">
        <location id="Л400">
            <country>България</country>
            <city>София</city>
            <street>Пиротска</street>
            <building_number>С598</building_number>
        </location>
        <phone>0888 674 8085</phone>
        <website>ЧерниЗърна.ком</website>
        <e-mail>ЧерниЗърна@кафе.ком</e-mail>
    </contacts>
    <employees>
        <employee id="Е40" position="Продавач" sex="Жена">
            <emp_name>Стела</emp_name>
            <salary>1000</salary>
            <age>30</age>
        </employee>
        <employee id="Е41" position="Продавач" sex="Жена">
            <emp_name>Михаела</emp_name>
            <salary>1000</salary>
            <age>30</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_2.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id = "2">
    <name>Сладко Кафе</name>
    <working_time>От 06 до 20</working_time>
    <products>
        <product id="П20">
            <price>4.50лв.</price>
            <product_name>Сладкиши</product_name>
            <description>
                Селекция от сладкиши направени с най-добрите съставки по традиционни рецепти от цял свят. 
                В перфектна комбинация с вашето сутрешно кафе, лесни за консумация, докато сте в движение и засищащи. Възхитителни и вкусни!
            </description>
            <food id="Х07" food_type = "Сладко">
                <food_name>Бисквити</food_name>
            </food>
            <food id="Х08" food_type = "Сладко">
                <food_name>Кексчета</food_name>
            </food>
            <food id="Х09" food_type = "Сладко">
                <food_name>Торти</food_name>
            </food>
            <food id="Х10" food_type = "Сладко">
                <food_name>Сладолед</food_name>
            </food>
            <image>сладко.jpg</image>
        </product>
            <product id="П21">
                <price>5.50лв.</price>
                <product_name>Палачинки</product_name>
                <description>
                    Че палачинките са любима закуска на малки и големи няма никакъв спор. 
                    Сигурно на пръсти се броят хората, които не ги обичат.
                    Със сиренце, сладко, конфитюр, шоколад, кашкавал или каквото там обичате,
                    те са вкусни, мекички, наслада за небцето и сетивата.
                </description>
                <food id="Х200" food_type = "Сладко">
                    <food_name>Палачинки с плодове</food_name>
                </food>
                <food id="Х201" food_type = "Сладко">
                    <food_name>Палачинки с шоколад</food_name>
                </food>
                <food id="Х202" food_type = "Солено">
                    <food_name>Палачинки с филе</food_name>
                </food>
                <image>палачинки.jpg</image>
            </product>
            <product id="П22">
                <price>4.50лв.</price>
                <product_name>Солени храни</product_name>
                <description>
                    Ръчно приготвени по оригинални рецепти на, пресни и сочни всеки ден, 
                    за възможно най-добрия старт на деня в комбинация с хубаво кафе!
                </description>
             <food  id="Х2024" food_type = "Солено">
                 <food_name>Кроасани</food_name>
             </food>
            <food id="Х2025" food_type = "Солено">
                <food_name>Мини сандвичи</food_name>
            </food>
            <food id="Х2026" food_type = "Солено">
                <food_name>Закуски</food_name>
            </food>
            <image>закуски.jpg</image>
        </product>
    </products>
    <contacts id="С09">
        <location id="Л090">
            <country>България</country>
            <city>София</city>
            <street>Витошка</street>
            <building_number>876р</building_number>
        </location>
        <phone>0889 876 432</phone>
        <website>СладкоКафе.ком</website>
        <e-mail>СладкоКафе@имейл.ком</e-mail>
    </contacts>
    <employees>
        <employee id="Е02" position="Готвач" sex="Мъж">
            <emp_name>Димитър Ангелов</emp_name>
            <salary>1000</salary>
            <age>28</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_18.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="2">
  <name>Черен рай</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П180">
      <price>3</price>
      <product_name>Шарени кафета</product_name>
      <coffee id="К180" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Капучино малина</coffee_name>
        <coffee_type>Лаваца</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К181" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Капучино лешник</coffee_name>
        <coffee_type>Лаваца</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К182" supplement_type="Захар" drink_type="Гореща">
        <coffee_name>Дълго кафе с портокал</coffee_name>
        <coffee_type>Лаваца</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
    </product>
  </products>
  <contacts id="С180">
    <location id="L180">
      <country>Ромъния</country>
      <city>Брашов</city>
      <street>Хеог</street>
      <building_number>т45</building_number>
    </location>
    <phone>08765432</phone>
    <website>Черен - рай.ро</website>
    <e-mail>Черен@рай</e-mail>
  </contacts>
  <employees>
    <employee id="E180" position="Продавач" sex="Мъж">
      <emp_name>Сашо</emp_name>
      <salary>600</salary>
      <age>30</age>
    </employee>
    <employee id="E181" position="Продавач" sex="Жена">
      <emp_name>Мария</emp_name>
      <salary>3</salary>
      <age>sdc</age>
    </employee>
    <employee id="E182" position="Продавач" sex="Жена">
      <emp_name>Бианка</emp_name>
      <salary>435</salary>
      <age>30</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_15.xml
<?xml version="1.0" encoding="utf-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="15">
  <name>Коста</name>
  <working_time>от 8 до 22</working_time>
  <products>
    <product id="П150">
      <price>4лв.</price>
      <product_name>Кафета</product_name>
      <coffee id="К150" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Късо кафе</coffee_name>
        <coffee_type>Коста</coffee_type>
      </coffee>
      <coffee id="К151" supplement_type="Без" drink_type="Гореща">
        <coffee_name>Дълго кафе</coffee_name>
        <coffee_type>Коста</coffee_type>
        <supplement_price>0</supplement_price>
      </coffee>
      <coffee id="К152" supplement_type="Сметана" drink_type="Гореща">
        <coffee_name>Виенско кафе</coffee_name>
        <coffee_type>Коста</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
      <coffee id="К153" supplement_type="Канела" drink_type="Гореща">
        <coffee_name>Канелено кафе</coffee_name>
        <coffee_type>Коста</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
      <coffee id="К154" supplement_type="Мляко" drink_type="Студена">
        <coffee_name>Бананово кафе</coffee_name>
        <coffee_type>Коста</coffee_type>
        <supplement_price>1лв.</supplement_price>
      </coffee>
    </product>
    <product id="П151">
      <price>6лв.</price>
      <product_name>Кексчета</product_name>
      <food id="Х150" food_type="Солено">
        <food_name>Кексче с шоколад</food_name>
      </food>
      <food id="Х151" food_type="Солено">
        <food_name>Кексче с малина</food_name>
      </food>
      <food id="Х152" food_type="Сладко">
        <food_name>Кексче с ягода</food_name>
      </food>
    </product>
  </products>
  <contacts id="Л2">
    <location id="C2">
      <country>България</country>
      <city>Шумен</city>
      <street>Хевд</street>
      <building_number>3424</building_number>
    </location>
    <phone>087654747</phone>
    <website>Стар-бъкс.ком</website>
    <e-mail>Стар@бъксс</e-mail>
  </contacts>
  <employees>
    <employee id="E150" position="Продавач" sex="Мъж">
      <emp_name>Слави</emp_name>
      <salary>800</salary>
      <age>30</age>
    </employee>
    <employee id="E151" position="Готвач" sex="Жена">
      <emp_name>Пламен</emp_name>
      <salary>1000</salary>
      <age>34</age>
    </employee>
  </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_19.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="19">
    <name>Чайка</name>
    <working_time>от 7:00 - до 20:00</working_time>
    <products>
        <product id="п190">
            <price>5.50лв.</price>
            <product_name>Кроасани</product_name>
            <description>
			Ръчно приготвени по оригинални рецепти на, пресни и сочни всеки ден, 
                    за възможно най-добрия старт на деня в комбинация с хубаво кафе!
			</description>
            <food id="X1901" food_type="Солено">
              <food_name>Кроасан с плодове</food_name>
            </food>
            <food id="X1902" food_type="Солено">
              <food_name>Кроасан със сирене</food_name>
            </food>
			      <food id="X1903" food_type="Солено">
              <food_name>Кроасан с шунка и кашкавал</food_name>
            </food>
			     <food id="X1904" food_type="Солено">
              <food_name>Кроасан с шунка и топено сирене</food_name>
            </food>
            <food id="X1905" food_type="Солено">
              <food_name>Кроасан с шоколад</food_name>
            </food>
            <food id="X1906" food_type="Солено">
              <food_name>Кроасан със сладко</food_name>
            </food>
            <food id="X1907" food_type="Солено">
              <food_name>Кроасан с масло</food_name>
            </food>
        </product>
        <product id="п191">
            <price>2лв</price>
            <product_name>Kафе</product_name>
            <description>най-яките кафета! Традиционни</description>
          <coffee id="к1910" drink_type ="Гореща" supplement_type = "Сметана">
              <coffee_name>Виенско кафе</coffee_name>
              <coffee_type>Cararro</coffee_type>
              <supplement_price>0.10лв</supplement_price>
            </coffee>
          <coffee id="к1911" drink_type ="Гореща" supplement_type = "Канела">
              <coffee_name>Капучно с канела</coffee_name>
              <coffee_type>Cararro</coffee_type>
              <supplement_price>0.50лв</supplement_price>
            </coffee>
        </product>
    </products>
    <contacts id="c19">
        <location id="Л19">
            <country>България</country>
            <city>София</city>
            <street>Граф Игнатиев</street>
            <building_number>65Д</building_number>
        </location>
        <phonииоe>0887347690</phonииоe>
        <website>СуперКафе.бг</website>
        <e-mail>СуперКафе@кафе.ком</e-mail>
    </contacts>
    <employees>
        <employee id="e190" position="Продавач" sex="Мъж">
            <emp_name>Димитър</emp_name>
            <salary>900</salary>
            <age>23</age>
        </employee>
        <employee id="e191" position="Продавач" sex="Мъж">
            <emp_name>Кайлита</emp_name>
            <salary>900</salary>
            <age>67</age>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/CoffeeHouse_1.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id="1" >
    <name>Всичко За Кафето</name>
    <working_time>От 06.00 до 20.00. Всеки ден</working_time>
    <products>
        <product id="К01">
            <price>2.50лв</price>
            <product_name>Класическо кафе</product_name>
            <description>
                Една от най-разпространените форми, под които пием любимото ни кафеено удоволствие е еспресото. 
                Създаването на чаша еспресо е процес, който изисква старание и внимание към детайла. Най-често разпространеният вид кафе, подходящ за еспресо е сорт Робуста.
                Той е с по-високо съдържание на кофеин и е по-евтин в сравнение с Арабиката, заради което се използва и в повечето търговски марки кафе. 
                Робустата оформя плътният каймак на еспресото и е по-малко чувствителна към температурата. 
                Истината е, че еспресото направено от смес 100% зърна Арабика обаче се смята за по-качествено, тъй като вкусът му е по-фин и по-ароматен.
            </description>
            <coffee id="К12"  supplement_type="Без" drink_type="Гореща">
                <coffee_name>Късо кафе</coffee_name>
                <coffee_type>Еспресо</coffee_type>
            </coffee>
            <coffee id="К11"  supplement_type="Без" drink_type="Гореща">
                <coffee_name>Дълго кафе</coffee_name>
                <coffee_type>Еспресо</coffee_type>
            </coffee>
            <image>кафе.jpg</image>
        </product>
        <product id="П01">
            <price>2.50лв</price>
            <product_name>Храна</product_name>
            <food id="Х011"  food_type="Солено">
                <food_name>Сандвич</food_name>
            </food>
        </product>
    </products>
    <contacts id="Л1">
        <location id="С1">
            <country>България</country>
            <city>Тутракан</city>
            <building_number>6544</building_number>
        </location>
        <phone>0887965783</phone>
        <website>ВсичкоЗаКафето-кафе.ком</website>
        <e-mail>ВсичкоЗаКафето@кафе.ком</e-mail>
    </contacts>
    <employees>
        <employee id="Е10" position="Управител" sex="Мъж">
            <emp_name>Петкан</emp_name>
            <salary>800</salary>
        </employee>
        <employee id="E11" position="Продавач" sex="Жена">
            <emp_name>Силвия</emp_name>
            <salary>700</salary>
        </employee>
        <employee id="E12" position="Чистач" sex="Жена">
            <emp_name>Магдалена</emp_name>
            <salary>920</salary>
        </employee>
    </employees>
</CoffeeHouse>

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_4.xml
<CoffeeHouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="file:/C:/Users/Bibi/Desktop/ASP/asp-proekt-novo-novo/XmlSample/App_Data/coffeeHouse.xsd" id = "4">
    <name>Всичко За Кафето</name>
    <working_time>От 06.00 до 20.00. Всеки ден</working_time>
    <products>
        <product id="П400">
            <price>100 лева</price>
            <product_name>Кафемашина</product_name>
            <description>
                За да се уверите, че винаги ще получите същото високо качество , с чудесен вкус, независимо дали сте у дома или навън. 
                Уверете се в лекотата на използване на Tassimo машината.
                Той върши цялата техническа , сложна работа , така че всичко, което трябва да направите е да натиснете един бутон!
                Можете да получавате всеки ден у дома перфектната чаша кафе!
            </description>
        </product>
        <product id="П401">
            <price>30 лева</price>
            <product_name>Машина за фрапе</product_name>
            <description></description>
        </product>
        <product id="П402">
            <price>10 лева</price>
            <product_name>Френска преса</product_name>
            <description>
                Френската преса е един от най-старите и удобни начини за приготвяне на кафе.
                С нея се работи лесно, не е скъпа и прави наистина добро кафе. 
                Още ли търсите начин да приготвите кафе със силен аромат, плътно тяло и наситен вкус? 
                Току що го открихте – незаменимата френска преса.
            </description>
        </product>
    </products>
    <contacts id="С400">
        <location id="L400">
            <country>България</country>
            <city>София</city>
            <street>Витошка</street>
            <building_number>С59</building_number>
        </location>
        <phone>0888 567 896</phone>
        <website>CoffeeHouse.com</website>
        <e-mail>CoffeeHouse@gmail.com</e-mail>
    </contacts>
    <employees>
        <employee id="Е03" position="Продавач" sex="Жена">
            <emp_name>Стела</emp_name>
            <salary>1000</salary>
            <age>30</age>
        </employee>
    </employees>
</CoffeeHouse>
