=== biannka/ASP_NET/XmlSample/App_Data/coffeeHouse.dtd
<!ELEMENT CoffeeHouse (name, working_time, products,gift?, contacts, employees)>
    <!ATTLIST CoffeeHouse id CDATA #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT working_time (#PCDATA) >
    <!ELEMENT products (product)+>
    <!ELEMENT product (price,product_name, description?, coffee*, food*, image*)>
        <!ATTLIST product id ID #REQUIRED>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT product_name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT coffee (coffee_name , coffee_type, supplement_price?)>
            <!ATTLIST coffee id ID #REQUIRED>
            <!ATTLIST coffee drink_type (Гореща|Студена) 'Гореща' >
            <!ELEMENT coffee_type (#PCDATA) >
            <!ELEMENT coffee_name (#PCDATA) >
            <!ELEMENT supplement_price (#PCDATA)>
            <!ATTLIST coffee supplement_type (Захар|Канела|Мляко|Сметана|Без) 'Без'>
        <!ELEMENT food (food_name)>
            <!ATTLIST food id ID #REQUIRED>
            <!ATTLIST food food_type (Солено|Сладко) #REQUIRED>
            <!ELEMENT food_name (#PCDATA)>
    <!ELEMENT gift (gift_name)>
        <!ATTLIST gift id ID #REQUIRED>
        <!ELEMENT gift_name (#PCDATA) >
        <!ATTLIST gift gift_type (Храна|Кафе|Отстъпка|Ваучер) #REQUIRED>
        <!ATTLIST gift gift_reason (Редовен|Покупка) #REQUIRED>
    <!ELEMENT contacts (location, phone, website, e-mail)>
        <!ATTLIST contacts id ID #REQUIRED>
        <!ELEMENT phone (#PCDATA) >
        <!ELEMENT e-mail (#PCDATA) >
        <!ELEMENT website (#PCDATA) >
        <!ELEMENT location (country?, city ,street?, building_number)>
            <!ATTLIST location id ID #REQUIRED>
            <!ELEMENT country (#PCDATA) >
            <!ELEMENT city (#PCDATA) >
            <!ELEMENT street (#PCDATA) >
            <!ELEMENT building_number (#PCDATA) >
    <!ELEMENT employees (employee)+>
        <!ELEMENT employee (emp_name, salary, age?)>
        <!ATTLIST employee id ID #REQUIRED >
        <!ATTLIST employee position (Продавач | Готвач | Чистач |  Управител) #REQUIRED>
        <!ATTLIST employee sex (Мъж| Жена) #REQUIRED>
        <!ELEMENT emp_name (#PCDATA) >
        <!ELEMENT salary (#PCDATA) >
        <!ELEMENT age (#PCDATA) >

=== biannka/ASP_NET/XmlSample/App_Data/XMLs/CoffeeHouse_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CoffeeHouse SYSTEM "file:/C:/Users/Bibi/Desktop/XML/final/CoffeeHouse.dtd">
<CoffeeHouse id="1" >
    <name>Всичко За Кафето</name>
    <working_time>От 06.00 до 20.00. Всеки ден</working_time>
    <products>
        <product id="К01">
            <price>2.00 лева</price>
            <product_name>Класическо кафе</product_name>
            <description>
                Една от най-разпространените форми, под които пием любимото ни кафеено удоволствие е еспресото. 
                Създаването на чаша еспресо е процес, който изисква старание и внимание към детайла. Най-често разпространеният вид кафе, подходящ за еспресо е сорт Робуста.
                Той е с по-високо съдържание на кофеин и е по-евтин в сравнение с Арабиката, заради което се използва и в повечето търговски марки кафе. 
                Робустата оформя плътният каймак на еспресото и е по-малко чувствителна към температурата. 
                Истината е, че еспресото направено от смес 100% зърна Арабика обаче се смята за по-качествено, тъй като вкусът му е по-фин и по-ароматен.
            </description>
            <coffee id="К12" drink_type = "Гореща">
                <coffee_name>Късо кафе</coffee_name>
                <coffee_type>Еспресо</coffee_type>
            </coffee>
            <coffee id="К11" drink_type = "Гореща">
                <coffee_name>Дълго кафе</coffee_name>
                <coffee_type>Еспресо</coffee_type>
            </coffee>
            <image>кафе.jpg</image>
        </product> 
    </products>
</CoffeeHouse>
